### ISSUE TITLE
Fix SAD-guess representation for open-shell systems

### ISSUE THREAD

**Issue by YAY-C** [lcmd-epfl/Q-stack#32]
Generating SPAHMs fails when using the SAD-guess with open-shell systems.
The Hcore matrix is returned as  'closed-shell' and the Veff computed from spherically averaged atomicHF densities is open-shell (tuple with alpha/beta matrices); adding them up return a fock matrix as tuple (2, Nbas, Nbas); which can not be handled by the solver.

**Careful code in branch has been modified to print more details and exits before computing the representations**

Run `test_SAD.py` to get traceback error:
```
pytest tests/test_SAD.py
```

**Comment by YAY-C** [comment]
The issue should be solved, I think ... 

Just not sure about whether the alpha and beta component of the Veff could be different, so I added a warning just in case.

**Comment by YAY-C** [comment]
@briling take a look, and if it seems fine to you we can merge!

**Comment by briling** [comment]
@YAY-C looks good, could you please make a PR?
