### ISSUE TITLE
Loading molecules for spahm

### ISSUE THREAD

**Issue by briling** [lcmd-epfl/Q-stack#33]
What is [this](../blob/master/qstack/spahm/rho/utils.py#L36) supposed to do?

```
        mols.append(compound.xyz_to_mol(xyzfile, basis, charge=0 if ch is None else ch,
                                        spin=0 if ch is None else sp, unit=units)) #TODO
```
I don't understand why `spin=0 if ch is None else sp`

**Comment by YAY-C** [comment]
Though I don't know if they change this behaviour in the more recent version of PySCF ...

**Comment by briling** [comment]
apparently `spin=0 if ch is None else sp` was a bug
