### ISSUE TITLE
Assertion Error using LB-guess with ECP

### ISSUE THREAD

**Issue by YAY-C** [lcmd-epfl/Q-stack#42]
So while I was re-generating **SPAHM-e** for Yuri's transition metal complexes with `LB` guess **and ECP**, I get an assertion error arising from [this test](https://github.com/lcmd-epfl/Q-stack/blob/2185097ca726ec86c8d2953dbc751db851707bf0/qstack/spahm/LB2020guess.py#L334).

How important is it ?
Do you know how to fix it ?

Here's a xyz to try out (comes from Yuri). params: `spin=4`, `charge=0`, `guess=LB`, `basis=minao`, `ecp=def2-svp`
[HOYHOS.xyz.txt](https://github.com/lcmd-epfl/Q-stack/files/15220714/HOYHOS.xyz.txt)

__carefull I had to change the file extension, gh wouldn't accept .xyz extensions :laughing:__

```
Traceback (most recent call last):
    e_spahm = qstack.spahm.compute_spahm.get_spahm_representation(mol, guess)
  File "qstack/spahm/compute_spahm.py", line 56, in get_spahm_representation
    e, v  = get_guess_orbitals(mol, guess, xc)
  File "qstack/spahm/compute_spahm.py", line 18, in get_guess_orbitals
    fock = guess(mol, xc)
  File "qstack/spahm/guesses.py", line 89, in LB
    return LB20(parameters='HF').Heff(mol)
  File "qstack/spahm/LB2020guess.py", line 353, in Heff
    self.H     = self.Hcore + self.HLB20(mol)
  File "qstack/spahm/LB2020guess.py", line 343, in HLB20
    self.check_coefficients(mol, acbasis)
  File "qstack/spahm/LB2020guess.py", line 337, in check_coefficients
    assert numpy.isclose(ch1, ch2)
AssertionError

```

**Comment by briling** [comment]
Yes I made a mistake so the inner shells were removed twice because there were 2 iodines

**Comment by YAY-C** [comment]
Ah yees I see it!
