### ISSUE TITLE
update_spahm-b

### ISSUE THREAD

**Issue by YAY-C** [lcmd-epfl/Q-stack#47]
There are a few changes I would like to PR:
- optional argument to use the same basis (`CC.bas`)  for all atom-pairs
- changes to generate representations for a single element-type in a structure
- `ecp` argument for CLI `parser`

*then I also have various some implementations for a better atom-pair bagging for global spahm-b, but these are not totally worked out yet*

**Is it ok if I included these changes in the same PR or do you want me to split**

**Comment by briling** [comment]
i think ecp should be together with other ecp changes

**Comment by YAY-C** [comment]
Ecp related changes are now at #48
