### ISSUE TITLE
Installation problem #1

### ISSUE THREAD

**Issue by jvschleicher** [lcmd-epfl/Q-stack#69]
Trying to install qstack from the .yml file fails for me with the error: 

Pip subprocess error:
ERROR: Invalid requirement: 'qstack/qstack-qml' (from line 16 of /home/<user>/condaenv.2liejdha.requirements.txt)
Hint: It looks like a path. File 'qstack/qstack-qml' does not exist.
failed
CondaEnvException: Pip failed

**Comment by liam-o-marsh** [comment]
oh... I think I see.
what was the working directory when you were trying to do that? It expects you to be inside the root directory of the repo
