### ISSUE TITLE
Installation problem #2

### ISSUE THREAD

**Issue by jvschleicher** [lcmd-epfl/Q-stack#70]
Trying to install qstack with 

pip install qstack[all] git+https://github.com/lcmd-epfl/Q-stack.git@master

failed with the error:
Collecting git+https://github.com/lcmd-epfl/Q-stack.git@master
  Cloning https://github.com/lcmd-epfl/Q-stack.git (to revision master) to /tmp/pip-req-build-9q5s_z64
  Running command git clone --quiet https://github.com/lcmd-epfl/Q-stack.git /tmp/pip-req-build-9q5s_z64
  Resolved https://github.com/lcmd-epfl/Q-stack.git to commit c6e487ea4c79b25265f523d26baccff600694e4d
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement qstack[all] (from versions: none)
ERROR: No matching distribution found for qstack[all]

- might be a workstation-specific problem?

**Comment by liam-o-marsh** [comment]
I think the problem is from the command itself:
it should have been `pip install "qstack[all] @ git+https://github.com/lcmd-epfl/Q-stack.git@master"`
